import React from 'react';
import CVAnalyzerComponent from '@/components/CVAnalyzer';

// Mock job data for the CV Analyzer
const jobs = [
  {
    id: 1,
    company: 'Amazon',
    position: 'Senior UI/UX Designer',
    tags: ['Full time', 'Senior level', 'Remote', 'UI/UX', 'Design'],
    hourlyRate: 65,
    location: 'San Francisco, CA',
    experience: 'Senior',
    perMonth: '$11,000',
    logoUrl: null,
    logo: 'amazon',
    isDraft: false,
  },
  {
    id: 2,
    company: 'Google',
    position: 'Frontend Developer',
    tags: ['Full time', 'Mid level', 'On-site', 'React', 'JavaScript'],
    hourlyRate: 55,
    location: 'Mountain View, CA',
    experience: 'Mid-level',
    perMonth: '$9,500',
    logoUrl: null,
    logo: 'google',
    isDraft: false,
  },
  {
    id: 3,
    company: 'Microsoft',
    position: 'Full Stack Engineer',
    tags: ['Full time', 'Senior level', 'Hybrid', 'Node.js', 'React', 'MongoDB'],
    hourlyRate: 60,
    location: 'Seattle, WA',
    experience: 'Senior',
    perMonth: '$10,400',
    logoUrl: null,
    logo: 'microsoft',
    isDraft: false,
  },
  {
    id: 4,
    company: 'Airbnb',
    position: 'Product Designer',
    tags: ['Contract', 'Mid level', 'Remote', 'UI/UX', 'Figma'],
    hourlyRate: 50,
    location: 'Remote',
    experience: 'Mid-level',
    perMonth: '$8,600',
    logoUrl: null,
    logo: 'airbnb',
    isDraft: false,
  },
  {
    id: 5,
    company: 'Salesforce',
    position: 'Frontend Developer',
    tags: ['Full time', 'Entry level', 'On-site', 'JavaScript', 'HTML/CSS'],
    hourlyRate: 45,
    location: 'San Francisco, CA',
    experience: 'Entry-level',
    perMonth: '$7,800',
    logoUrl: null,
    logo: 'salesforce',
    isDraft: false,
  },
  {
    id: 6,
    company: 'Adobe',
    position: 'UX Researcher',
    tags: ['Full time', 'Senior level', 'Hybrid', 'User Research', 'Prototyping'],
    hourlyRate: 58,
    location: 'San Jose, CA',
    experience: 'Senior',
    perMonth: '$10,000',
    logoUrl: null,
    logo: 'adobe',
    isDraft: false,
  },
  {
    id: 7,
    company: 'Netflix',
    position: 'Backend Developer',
    tags: ['Full time', 'Senior level', 'On-site', 'Java', 'Microservices'],
    hourlyRate: 65,
    location: 'Los Gatos, CA',
    experience: 'Senior',
    perMonth: '$11,200',
    logoUrl: null,
    logo: 'netflix',
    isDraft: false,
  },
  {
    id: 8,
    company: 'Twitter',
    position: 'Mobile Developer',
    tags: ['Contract', 'Mid level', 'Remote', 'React Native', 'iOS', 'Android'],
    hourlyRate: 52,
    location: 'Remote',
    experience: 'Mid-level',
    perMonth: '$9,000',
    logoUrl: null,
    logo: 'twitter',
    isDraft: false,
  }
];

// Mock course data for the CV Analyzer
const courses = [
  {
    id: 1,
    title: 'React - The Complete Guide',
    instructor: 'Dr. Rajesh Sharma',
    level: 'Intermediate',
    duration: '40 hours',
    lessons: 424,
    students: 125000,
    rating: 4.8,
    price: '$59',
    image: 'https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?auto=format&fit=crop&q=80&w=300&h=200',
    color: 'bg-blue-600',
    popular: true,
    category: 'Web Development'
  },
  {
    id: 2,
    title: 'UI/UX Design Masterclass',
    instructor: 'Jessica Wong',
    level: 'All Levels',
    duration: '35 hours',
    lessons: 215,
    students: 78500,
    rating: 4.7,
    price: '$79',
    image: 'https://images.unsplash.com/photo-1561070791-2526d30994b5?auto=format&fit=crop&q=80&w=300&h=200',
    color: 'bg-purple-600',
    popular: true,
    category: 'Design'
  },
  {
    id: 3,
    title: 'Node.js - From Zero to Expert',
    instructor: 'Michael Johnson',
    level: 'Advanced',
    duration: '38 hours',
    lessons: 320,
    students: 64300,
    rating: 4.9,
    price: '$69',
    image: 'https://images.unsplash.com/photo-1648737966769-98fa88fe6e8f?auto=format&fit=crop&q=80&w=300&h=200',
    color: 'bg-green-600',
    popular: false,
    category: 'Backend Development'
  },
  {
    id: 4,
    title: 'DevOps Engineering Professional',
    instructor: 'Alex Rodriguez',
    level: 'Advanced',
    duration: '45 hours',
    lessons: 280,
    students: 42100,
    rating: 4.6,
    price: '$89',
    image: 'https://images.unsplash.com/photo-1596474072382-c89372d1bc8a?auto=format&fit=crop&q=80&w=300&h=200',
    color: 'bg-red-600',
    popular: false,
    category: 'DevOps'
  },
  {
    id: 5,
    title: 'Python Programming Fundamentals',
    instructor: 'Sarah Chen',
    level: 'Beginner',
    duration: '30 hours',
    lessons: 210,
    students: 156000,
    rating: 4.9,
    price: '$49',
    image: 'https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?auto=format&fit=crop&q=80&w=300&h=200',
    color: 'bg-yellow-600',
    popular: true,
    category: 'Programming'
  },
  {
    id: 6,
    title: 'Modern JavaScript: ES6 and Beyond',
    instructor: 'David Miller',
    level: 'Intermediate',
    duration: '25 hours',
    lessons: 180,
    students: 92400,
    rating: 4.7,
    price: '$55',
    image: 'https://images.unsplash.com/photo-1579468118864-1b9ea3c0db4a?auto=format&fit=crop&q=80&w=300&h=200',
    color: 'bg-blue-500',
    popular: false,
    category: 'Web Development'
  },
  {
    id: 7,
    title: 'AWS Cloud Architect Certification',
    instructor: 'Samantha Taylor',
    level: 'Advanced',
    duration: '50 hours',
    lessons: 340,
    students: 37800,
    rating: 4.8,
    price: '$99',
    image: 'https://images.unsplash.com/photo-1603695762547-fba8575b9a23?auto=format&fit=crop&q=80&w=300&h=200',
    color: 'bg-orange-500',
    popular: true,
    category: 'Cloud Computing'
  },
  {
    id: 8,
    title: 'Mobile App Development with React Native',
    instructor: 'Kevin Lee',
    level: 'Intermediate',
    duration: '35 hours',
    lessons: 245,
    students: 68900,
    rating: 4.6,
    price: '$65',
    image: 'https://images.unsplash.com/photo-1581291518633-83b4ebd1d83e?auto=format&fit=crop&q=80&w=300&h=200',
    color: 'bg-indigo-600',
    popular: false,
    category: 'Mobile Development'
  }
];

const CVAnalyzer = () => {
  return (
    <div className="container mx-auto py-8 px-4">
      {/* Remove the header as it's already in the component */}
      <CVAnalyzerComponent jobs={jobs} courses={courses} />
    </div>
  );
};

export default CVAnalyzer; 